version: "3.8"

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"  # Mappe le ports 9092 du conteneur au port 9092 de la machine hôte
      - "9093:9093"  # Accès EXTERNE pour votre script Python local
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller # joue le role de broker et listener au meme temps
      # KAFKA_LISTENERS définit les ports que Kafka ouvre réellement.
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094 # Internal : services dans le même Docker network, External : Clients hors Docker comme ton PC, CONTROLLER : communication entre les noeuds qui joue role de Controller
      # Définit comment les clients (consumers,producers)
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXTERNAL://localhost:9093
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ./main:/opt/main  # j'ai ajouté cela pour partie de dag afin d'avoir file data_ingestion local sur container
      - kafka_data:/var/lib/kafka/data

  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - CASSANDRA_CLUSTER_NAME=RedditCluster
        - CASSANDRA_DC=datacenter1
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        - MAX_HEAP_SIZE=512M
        - HEAP_NEWSIZE=100M
      volumes:
        - cassandra_data:/var/lib/cassandra
      healthcheck:
        test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
        interval: 30s
        timeout: 10s
        retries: 5

  # ---  SERVICE D'INITIALISATION ---
  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    depends_on:
      - cassandra
    volumes:
      - ./init.cql:/init.cql  # On monte le fichier SQL dans le conteneur
    command: >
      bash -c "echo '⏳ Attente de Cassandra...' &&
      while ! cqlsh cassandra 9042 -e 'DESCRIBE KEYSPACES' > /dev/null 2>&1; do sleep 5; done &&
      echo '✅ Cassandra est prêt ! Création des tables...' &&
      cqlsh cassandra 9042 -f /init.cql &&
      echo '🎉 Tables créées avec succès !'"

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-spark:3.5.1
    container_name: spark-master
    env_file:
      - .env
    environment:
      SPARK_MODE: master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"] # commande executer a chaque fois que le conteneur démarre
    ports:
      - "8083:8080"
      - "7077:7077"
    volumes:
      - ./spark:/opt/spark/work-dir
      - ./models:/opt/spark/models
    depends_on:
      - broker
      - cassandra

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-spark:3.5.1
    container_name: spark-worker
    env_file:
      - .env
    environment:
      SPARK_MODE: worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    ports:
      - "8084:8081"
    volumes:
      - ./spark:/opt/spark/work-dir
      - ./models:/opt/spark/models
    depends_on:
      - spark-master
      - cassandra
  
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27018:27017"  # Changed to 27018 to avoid conflict with local MongoDB
    environment:
      MONGO_INITDB_DATABASE: reddit_backup_local
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
      image: apache/airflow:2.7.1
      depends_on:
        - airflow-postgres
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      # Cette commande crée l'utilisateur admin et initialise les tables
      command: >
        bash -c "airflow db init &&
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin"
  airflow-postgres:
      image: postgres:15
      container_name: airflow-postgres  # Force le nom pour le DNS Docker
      environment:
        POSTGRES_USER: airflow
        POSTGRES_PASSWORD: airflow
        POSTGRES_DB: airflow
      ports:
        - "5432:5432"
      volumes:
        - airflow-db:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.7.1
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      _PIP_ADDITIONAL_REQUIREMENTS: "requests praw==7.8.1 python-dotenv kafka-python Mastodon.py"
    ports:
      - "8091:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./main:/opt/airflow/main 
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.7.1
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-webserver
    env_file:
          - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "requests praw==7.8.1 python-dotenv kafka-python Mastodon.py"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./main:/opt/airflow/main  
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler
    restart: always

networks:
  default:
    name: reddit-network
    driver: bridge

volumes:
  kafka_data:
  cassandra_data:
  mongodb_data:
  airflow-db:
